---
title: "Spatial_Experiment"
author: "Hainan Xu"
date: "05/06/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Sapatial Experiment

```{r }
library(SpatialExperiment)
example(read10xVisium, echo = FALSE)
spe
head(spatialCoords(spe))
spatialCoordsNames(spe)
head(colnames(spe))

spi<-getImg(spe)
identical(spi,imgData(spe)$data[[1]])

plot(imgRaster(spe))

```

## 2.Object Construction
### Mannually



```{r }
n<-length(z<-letters)
y<-matrix(nrow = n,ncol = n)
cd<-DataFrame(x = seq(n), y=seq(n),z)

spe1<-SpatialExperiment(assay =y,
                        colData = cd,
                        spatialCoordsNames = c("x","y"))

xy <- as.matrix(cd[, c("x", "y")])

spe2<-SpatialExperiment(
    assay=y,
    colData =cd['z'],
    spatialCoords = xy)

n <- 10; m <- 20
y <- matrix(nrow = n, ncol = m)
cd <- DataFrame(x = seq(m), y = seq(m))
xy<-matrix(nrow=m,ncol=2)
colnames(xy)<-c("x","y")

SpatialExperiment(
  assay=y,
  colData=cd,
  spatialCoordsNames=c("x","y"),
  spatialCoords = xy)
)

```
Build an SpatialExperiment object.#cannot read sce
```{R}
dir <- system.file(
   file.path("extdata", "10xVisium", "section1", "outs"),
   package = "SpatialExperiment")

fnm <- file.path(dir, "raw_feature_bc_matrix")
sce <- DropletUtils::read10xCounts(fnm)


img <- readImgData(
    path = file.path(dir, "spatial"),
    sample_id = "foo")

fnm <- file.path(dir, "spatial", "tissue_positions_list.csv")
xyz <- read.csv(fnm, header = FALSE,
    col.names = c(
        "barcode", "in_tissue", "array_row", "array_col",
        "pxl_row_in_fullres", "pxl_col_in_fullres"))

```

```{R}
dir <- system.file(
    file.path("extdata", "10xVisium"),
    package = "SpatialExperiment")

sample_ids <- c("section1", "section2")
samples <- file.path(dir, sample_ids, "outs")

(spe10x <- read10xVisium(samples, sample_ids,
    type = "sparse", data = "raw",
    images = "lowres", load = FALSE))
```

```{R}
n <- 1e3  # number of molecules
ng <- 50  # number of genes
nc <- 20  # number of cells

# sample xy-coordinates in [0, 1]
x <- runif(n)
y <- runif(n)


# assign each molecule to some gene-cell pair
gs <- paste0("gene", seq(ng))
gs
cs
cs <- paste0("cell", seq(nc))
gene <- sample(gs, n, TRUE)

cell <- sample(cs, n, TRUE)
# assure gene & cell are factors so that
# missing observations aren't dropped
gene <- factor(gene, gs)
cell <- factor(cell, cs)
df <- data.frame(gene, cell, x, y)
head(df)

# construct 'BumpyMatrix' # not work for my current version of R

library(BumpyMatrix)
mol <- splitAsBumpyMatrix(
    df[, c("x", "y")], 
    row = gene, col = cell)
y[1:5, 1:5]
```

```{R}
y<- with(df,table(gene,cell))
y <- as.matrix(unclass(y))

# construct SpatialExperiment
spe <- SpatialExperiment(
    assays = list(
        counts = y, 
        molecules = mol))
spe

molecules(spe)
```


```{R}
sub <- spe[, spe$sample_id == "section1"]
sub <- spe1[, colData(spe1)$in_tissue]
sum(colData(spe)$in_tissue) == ncol(sub)
```

```{R}
spe1 <- spe2 <- spe
spe3 <- cbind(spe1, spe2)
unique(spe3$sample_id)
```

```{R}
spe1 <- spe2 <- spe
spe1$sample_id <- paste(spe1$sample_id, "A", sep = ".")
spe2$sample_id <- paste(spe2$sample_id, "B", sep = ".")

# combine into single object
spe3 <- cbind(spe1, spe2)

unique(spe3$sample_id)

```

```{R}
new <- spe3$sample_id
new[1] <- "section2.A"
spe3$sample_id <- new


```

```{r}
spi <- getImg(spe)

```